'use client';
import {useState} from 'react';import {ArrowLeft,ArrowRight,Check} from 'lucide-react';import {serviceShowrooms} from '@/data/service-showrooms';import styles from './quote.module.css';
type Data={name:string;email:string;phone:string;source:string;business:string;businessAbout:string;service:string;budget:string;timeline:string;details:string};
const initial:Data={name:'',email:'',phone:'',source:'',business:'',businessAbout:'',service:'',budget:'',timeline:'',details:''};
const steps=['Contact','Business','Project','Details'];
export function QuoteForm({email,initialService}:{email:string;initialService:string}){const[step,setStep]=useState(0);const[data,setData]=useState({...initial,service:initialService});const[error,setError]=useState('');const update=(key:keyof Data,value:string)=>setData(current=>({...current,[key]:value}));
 const valid=()=>{if(step===0)return data.name&&data.email.includes('@');if(step===1)return data.business&&data.businessAbout;if(step===2)return data.service&&data.budget&&data.timeline;return data.details.length>=20};
 const next=()=>{if(!valid()){setError('Complete the required fields before continuing.');return}setError('');setStep(current=>Math.min(3,current+1));window.scrollTo({top:250,behavior:'smooth'})};
 const submit=()=>{if(!valid()){setError('Please provide a little more project detail.');return}const service=serviceShowrooms.find(item=>item.slug===data.service)?.title??data.service;const body=[`Name: ${data.name}`,`Email: ${data.email}`,`Phone: ${data.phone||'Not provided'}`,`Referral source: ${data.source||'Not provided'}`,`Business: ${data.business}`,`About the business: ${data.businessAbout}`,`Service: ${service}`,`Budget: ${data.budget}`,`Timeline: ${data.timeline}`,'',`Project details:`,data.details].join('\n');window.location.href=`mailto:${email}?subject=${encodeURIComponent(`${service} quote request from ${data.name}`)}&body=${encodeURIComponent(body)}`};
 return <section className={styles.formShell}><div className={styles.progress}>{steps.map((label,index)=><div className={index===step?styles.current:index<step?styles.done:''} key={label}><i>{index<step?<Check/>:index+1}</i><span>{label}</span></div>)}</div><div className={styles.bar}><i style={{width:`${(step+1)*25}%`}}/></div><div className={styles.panel}>
  {step===0?<><header><h2>Contact information</h2><p>How can I reach you?</p></header><div className={styles.fields}><label>Name *<input value={data.name} onChange={e=>update('name',e.target.value)} autoComplete="name"/></label><label>Email *<input type="email" value={data.email} onChange={e=>update('email',e.target.value)} autoComplete="email"/></label><label>Phone number<input value={data.phone} onChange={e=>update('phone',e.target.value)} autoComplete="tel"/></label><label>How did you hear about me?<input value={data.source} onChange={e=>update('source',e.target.value)}/></label></div></>:null}
  {step===1?<><header><h2>Your business</h2><p>Help me understand what you do.</p></header><div className={styles.fields}><label>Business or brand name *<input value={data.business} onChange={e=>update('business',e.target.value)}/></label><label className={styles.wide}>Tell me about the business *<textarea rows={6} value={data.businessAbout} onChange={e=>update('businessAbout',e.target.value)} placeholder="What do you offer, and who do you serve?"/></label></div></>:null}
  {step===2?<><header><h2>Project scope</h2><p>What are you looking for?</p></header><div className={styles.block}><strong>Service you are interested in *</strong><div className={styles.options}>{serviceShowrooms.map(item=><button type="button" className={data.service===item.slug?styles.selected:''} onClick={()=>update('service',item.slug)} key={item.slug}>{data.service===item.slug?<Check/>:null}{item.title}</button>)}</div></div><div className={styles.block}><strong>Budget range *</strong><div className={styles.options}>{['Under $1,000','$1,000–$3,000','$3,000–$7,500','$7,500+','Let’s discuss'].map(item=><button type="button" className={data.budget===item?styles.selected:''} onClick={()=>update('budget',item)} key={item}>{item}</button>)}</div></div><div className={styles.block}><strong>When are you ready to start? *</strong><div className={styles.options}>{['Immediately','Within 1 month','1–3 months','Just exploring'].map(item=><button type="button" className={data.timeline===item?styles.selected:''} onClick={()=>update('timeline',item)} key={item}>{item}</button>)}</div></div></>:null}
  {step===3?<><header><h2>Project details</h2><p>Help me understand the outcome you want.</p></header><label className={styles.detail}>Tell me more *<textarea rows={9} value={data.details} onChange={e=>update('details',e.target.value)} placeholder="Describe the problem, desired outcome, important features and anything I should know..."/><small>Include what is not working today and what success should look like.</small></label></>:null}
  {error?<p className={styles.error}>{error}</p>:null}<footer>{step>0?<button type="button" className={styles.backButton} onClick={()=>{setError('');setStep(current=>current-1)}}><ArrowLeft/> Back</button>:<span/>}{step<3?<button type="button" className={styles.nextButton} onClick={next}>Continue <ArrowRight/></button>:<button type="button" className={styles.nextButton} onClick={submit}>Send request <ArrowRight/></button>}</footer>
 </div></section>}
