import type {Metadata} from 'next';
import styles from '../profile-pages.module.css';

export const metadata:Metadata={title:'Experience',description:'Detailed professional experience, contributions and engineering progression of Barnabas Mikel.'};

const roles=[
  {id:'imisi-health',date:'APR 2026 — PRESENT',role:'Frontend Engineer',company:'Imisi Health',lead:'Building dependable product interfaces and API-driven workflows for digital healthcare products in a professional engineering team.',contributions:['Built responsive interfaces across healthcare product flows','Created and improved reusable frontend components','Integrated application interfaces with backend APIs','Contributed code-quality and product-experience improvements'],practice:['Responsive UI engineering','Component architecture','API-driven state','Team-based product delivery'],evidence:'42 healthcare screens represented in the portfolio summary',boundary:'Company work presented without exposing private product information'},
  {id:'synlo',date:'NOV 2025 — FEB 2026',role:'Lead Frontend Developer & UI/UX Designer',company:'Synlo',lead:'Led frontend implementation and interface design for a SocialFi product spanning discovery, matchmaking and AI-assisted interactions.',contributions:['Translated product ideas into structured interface flows','Designed and implemented responsive application screens','Maintained consistency across a multi-screen product experience','Connected product thinking, UI design and frontend delivery'],practice:['Frontend leadership','UI/UX design','Design-to-code execution','Responsive product systems'],evidence:'21 SocialFi screens designed and coded',boundary:'Role scope and verified output stated without fabricated performance metrics'},
  {id:'vin-startup-project',date:'NOV 2024 — JAN 2025',role:'Full-Stack Engineer',company:'VIN Startup Project',lead:'Built multimodal AI interfaces and the supporting application layer for an early-stage product initiative.',contributions:['Developed interfaces for multimodal AI interactions','Built Node.js and Express REST API workflows','Connected frontend behavior to server-side services','Worked with serverless product architecture'],practice:['Full-stack development','REST API design','AI interface integration','Serverless workflows'],evidence:'Technical scope documented through portfolio experience',boundary:'No unverified adoption or business-impact claims'},
];

export default function ExperiencePage(){return <main className={styles.page}>
  <section className={styles.hero}><span className="eyebrow">EXPERIENCE / PROFESSIONAL PROGRESSION</span><h1>Work behind<br/>the résumé.</h1><p>A closer look at the responsibilities, contribution areas and engineering progression behind each role.</p><div className={styles.heroActions}><a className="button black" href="/Barnabas-Mikel-Resume.pdf" download>Download résumé ↓</a><a className="button" href="mailto:mrbarnx@gmail.com?subject=Opportunity%20for%20Barnabas">Discuss an opportunity →</a></div><div className={styles.proofStrip}><div><strong>3</strong><span>Professional chapters</span></div><div><strong>Frontend</strong><span>Strongest discipline</span></div><div><strong>Full-stack</strong><span>Growing product scope</span></div><div><strong>AI</strong><span>Integration experience</span></div></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><div><span className="eyebrow">ROLE TIMELINE</span><h2>Responsibilities, not job-title decoration.</h2></div><p>Each entry separates what I contributed, the engineering practices involved and the evidence that can be shared responsibly.</p></div><div className={styles.timeline}>{roles.map(role=><article className={styles.role} id={role.id} key={role.company}><time className={styles.roleDate}>{role.date}</time><div><span className={styles.roleMeta}>{role.company}</span><h2>{role.role}</h2><p className={styles.roleLead}>{role.lead}</p><div className={styles.roleDetails}><div className={styles.detail}><h3>Contribution areas</h3><ul>{role.contributions.map(item=><li key={item}>{item}</li>)}</ul></div><div className={styles.detail}><h3>Engineering practice</h3><ul>{role.practice.map(item=><li key={item}>{item}</li>)}</ul></div></div><div className={styles.evidence}><span>{role.evidence}</span><small>{role.boundary}</small></div></div></article>)}</div></section>
  <section className={styles.section}><div className={styles.sectionHead}><div><span className="eyebrow">RECRUITER SUMMARY</span><h2>How I work.</h2></div><p>The consistent thread across these roles is moving from visual implementation toward complete, maintainable product engineering.</p></div><div className={styles.recruiterGrid}><article><h3>Product-minded</h3><p>I connect implementation choices to user flows, clarity and the purpose of the product.</p></article><article><h3>Evidence-conscious</h3><p>I separate verified work from proposed outcomes and respect confidential company boundaries.</p></article><article><h3>Always deepening</h3><p>I am expanding from frontend strength into backend engineering, AI integrations and automation systems.</p></article></div></section>
  <section className={styles.darkCta}><div><span className="eyebrow light">NEXT CHAPTER</span><h2>Looking for a product-focused engineer?</h2><p>Explore the project case studies or reach out with the role, product and problem your team is working on.</p></div><a href="mailto:mrbarnx@gmail.com?subject=Engineering%20Opportunity">Contact me ↗</a></section>
</main>}
