import type {Metadata} from 'next';
import {getProfessionalContent,publishedByOrder} from '@/lib/cms/publicProfessional';
import styles from '../profile-pages.module.css';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Experience',description:'Detailed professional experience, contributions and software engineering progression of Barnabas Mikel.'};
export default async function ExperiencePage(){
 const content=await getProfessionalContent();const roles=publishedByOrder(content.experience);
 return <main className={styles.page}>
 <section className={styles.hero}><span className="eyebrow">EXPERIENCE / PROFESSIONAL PROGRESSION</span><h1>Work behind<br/>the résumé.</h1><p>A closer look at the responsibilities, contribution areas and engineering decisions behind each role.</p><div className={styles.heroActions}><a className="button black" href="/Barnabas-Mikel-Resume.pdf" download>Download résumé ↓</a><a className="button" href="mailto:mrbarnx@gmail.com?subject=Opportunity%20for%20Barnabas">Discuss an opportunity →</a></div><div className={styles.proofStrip}><div><strong>{roles.length}</strong><span>Professional chapters</span></div><div><strong>Software</strong><span>Core discipline</span></div><div><strong>Full-stack</strong><span>Product scope</span></div><div><strong>AI</strong><span>Engineering direction</span></div></div></section>
 <section className={styles.section}><div className={styles.sectionHead}><div><span className="eyebrow">ROLE TIMELINE</span><h2>Responsibilities, not job-title decoration.</h2></div><p>Each entry separates what I contributed, the engineering practices involved and the evidence that can be shared responsibly.</p></div><div className={styles.timeline}>{roles.map(role=><article className={styles.role} id={role.slug} key={role.slug}><time className={styles.roleDate}>{role.date}</time><div><span className={styles.roleMeta}>{role.company}</span><h2>{role.role}</h2><p className={styles.roleLead}>{role.lead}</p><div className={styles.roleDetails}><div className={styles.detail}><h3>Contribution areas</h3><ul>{role.contributions.map(item=><li key={item}>{item}</li>)}</ul></div><div className={styles.detail}><h3>Engineering practice</h3><ul>{role.practices.map(item=><li key={item}>{item}</li>)}</ul></div></div><div className={styles.evidence}><span>{role.evidence}</span><small>{role.boundary}</small></div></div></article>)}</div></section>
 <section className={styles.section}><div className={styles.sectionHead}><div><span className="eyebrow">RECRUITER SUMMARY</span><h2>How I work.</h2></div><p>The consistent thread is building maintainable software across product interfaces, backend workflows, APIs and AI-enabled systems.</p></div><div className={styles.recruiterGrid}><article><h3>Product-minded</h3><p>I connect implementation decisions to user flows, operational needs and the purpose of the product.</p></article><article><h3>Evidence-conscious</h3><p>I separate verified work from proposed outcomes and respect confidential company boundaries.</p></article><article><h3>Systems-oriented</h3><p>I combine a strong frontend foundation with full-stack development, AI integration and practical automation.</p></article></div></section>
 <section className={styles.darkCta}><div><span className="eyebrow light">NEXT CHAPTER</span><h2>Looking for a software engineer?</h2><p>Explore the project case studies or reach out with the role, product and problem your team is working on.</p></div><a href="mailto:mrbarnx@gmail.com?subject=Engineering%20Opportunity">Contact me ↗</a></section>
 </main>;
}