import { deletePromptResource, publishPromptResource, savePromptResourceDraft } from '../content-actions';
import { ConfirmDeleteButton } from './ConfirmDeleteButton';
import type { DownloadDocument } from './StudioResourceForm';
import styles from '../content.module.css';
type Row=Record<string,unknown>;

export function PromptResourceForm({row={},documents=[]}:{row?:Row;documents?:DownloadDocument[]}){
  const currentDownload=String(row.download_path??'');
  return <form className={styles.form} action={savePromptResourceDraft}>
    <input type="hidden" name="id" value={String(row.id??'')}/>
    <section className={styles.section}><h2>Prompt identity</h2><div className={styles.fields}><label>Number label<input name="number_label" defaultValue={String(row.number_label??'')}/></label><label>Title<input required name="title" defaultValue={String(row.title??'')}/></label><label>Slug<input required name="slug" defaultValue={String(row.slug??'')}/></label><label>Category<input required name="category" defaultValue={String(row.category??'')}/></label><label>Sort order<input name="sort_order" type="number" min="0" defaultValue={String(row.sort_order??0)}/></label><label className={styles.check}><input type="checkbox" name="featured" defaultChecked={Boolean(row.featured)}/>Featured</label></div></section>
    <section className={styles.section}><h2>Prompt content</h2><div className={styles.stack}><label>Short summary<textarea required name="short_summary" rows={2} defaultValue={String(row.short_summary??'')}/></label><label>Description<textarea required name="description" rows={4} defaultValue={String(row.description??'')}/></label><label>Full prompt<textarea required name="prompt_text" rows={16} defaultValue={String(row.prompt_text??'')}/></label><label>Best for<textarea name="best_for" rows={3} defaultValue={String(row.best_for??'')}/></label><label>Tools — one per line<textarea name="tools" rows={4} defaultValue={Array.isArray(row.tools)?row.tools.join('\n'):''}/></label><label>Tutorial steps — one per line<textarea name="tutorial_steps" rows={6} defaultValue={Array.isArray(row.tutorial_steps)?row.tutorial_steps.join('\n'):''}/></label></div></section>
    <section className={styles.section}><h2>Optional download</h2><div className={styles.stack}><label>Select uploaded document<select name="document_url" defaultValue={documents.some(x=>x.url===currentDownload)?currentDownload:''}><option value="">No uploaded document selected</option>{documents.map(document=><option value={document.url} key={document.url}>{document.name} · {document.type}</option>)}</select><small>Upload a PDF or Markdown file in Media Library, then select it here.</small></label><div className={styles.fields}><label>Manual download URL or path<input name="download_path" defaultValue={currentDownload}/></label><label>Legacy source path<input name="source_path" defaultValue={String(row.source_path??'')}/></label></div></div></section>
    <div className={styles.formActions}>{row.id?<ConfirmDeleteButton action={deletePromptResource} label="prompt" className={styles.secondary}/>:null}<button type="submit" className={styles.secondary}>Save draft</button><button type="submit" className={styles.button} formAction={publishPromptResource}>Save & publish</button></div>
  </form>;
}
